{
 "title": "AWS Cost Explorer",
 "time": { "from": "now/y", "to": "now" },
 "panels": [
  {
   "title": "Last Month Costs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    { "target": "Last Month Aggregated", "type": "table" }
   ]
  },
  {
   "title": "Month to Date Costs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    { "target": "Month to Date Aggregated", "type": "table" }
   ]
  },
  {
   "title": "Costs History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Year to Date Aggregated", "type": "timeserie" }
   ]
  }
 ]
}